shotgunsoftware/tk-config-default2

core/core_api.yml

In conjunction with https://github.com/shotgunsoftware/tk-core/pull/579

#35379 Adds a `core_api.yml` file

---

core/hooks/pick_environment.py
env/includes/settings/tk-desktop.yml
env/site.yml

This allows the Shotgun Desktop to be run from `tk-config-basic2`.

For #46904, site level for default2

---

.gitignore
env/includes/app_locations.yml
env/includes/frameworks.yml
env/includes/settings/tk-multi-workfiles2.yml

tk-multi-workfile2 settings to leverage deferred queries by default.

For #38483, new wf2 settings

---

env/includes/settings/tk-flame.yml
env/includes/settings/tk-multi-loader2.yml

JIRA: SMOK-49215
Enable loader in advanced configuration by default

Flame: Add multi-loader2 in default configuration

---

env/includes/settings/tk-flame.yml

JIRA: SMOK-49281
Enable shotgun panel in advanced configuration

Enable Shotgun Panel in Flame

---

env/includes/settings/tk-flame.yml

JIRA: SMOK-49281 SMOK-49215
SMOK-49281 - Enable shotgun panel in advanced configuration
SMOK-49215 - Enable loader in advanced configuration by default

Enable Shotgun Panel and Loader in Flame start in a Shot

---

env/includes/app_locations.yml
env/includes/engine_locations.yml

JIRA: SMOK-49294
Update tk-flame to v.1.14.4
Update tk-flame-export to v1.9.1
Update tk-flame-review to v1.3.0

Use PyExporter in shotgun for thumbnail generation

---

env/includes/app_locations.yml
env/includes/engine_locations.yml

Shotgun Loader integration in Flame: Improve batch setup creation

---

core/core_api.yml
env/includes/app_locations.yml
env/includes/settings/tk-desktop.yml

SG-8474 Adds developer utils

---

env/asset_step.yml
env/includes/app_locations.yml
env/includes/engine_locations.yml
env/includes/frameworks.yml
env/includes/settings/tk-desktop2.yml
env/project.yml
env/shot_step.yml
env/site.yml

This adds tk-desktop2 with the same configuration as exists for tk-desktop.

SG-9252: Adds tk-desktop2 to the same environments that tk-desktop is in.

---

env/includes/engine_locations.yml

Update tk-flame to v1.14.7

---

core/templates.yml
env/asset.yml
env/asset_step.yml
env/includes/engine_locations.yml
env/includes/frameworks.yml
env/includes/settings/tk-aftereffects.yml
env/includes/settings/tk-aftereffectscc.yml
env/includes/settings/tk-desktop.yml
env/includes/settings/tk-multi-loader2.yml
env/includes/settings/tk-multi-publish2.yml
env/includes/settings/tk-multi-shotgunpanel.yml
env/includes/settings/tk-multi-snapshot.yml
env/includes/settings/tk-multi-workfiles2.yml
env/project.yml
env/shot.yml
env/shot_step.yml
env/site.yml

Attention this needs to be merged after the release of:
tk-framework-adobe
tk-aftereffectscc
tk-photoshopcc
tk-multi-launchapp

[tk-framework-adobe] changes for tk-aftereffectscc and tk-framework-adobe

---

core/templates.yml
env/asset.yml
env/asset_step.yml
env/includes/engine_locations.yml
env/includes/frameworks.yml
env/includes/settings/tk-aftereffects.yml
env/includes/settings/tk-desktop.yml
env/includes/settings/tk-multi-loader2.yml
env/includes/settings/tk-multi-publish2.yml
env/includes/settings/tk-multi-shotgunpanel.yml
env/includes/settings/tk-multi-snapshot.yml
env/includes/settings/tk-multi-workfiles2.yml
env/project.yml
env/shot.yml
env/shot_step.yml
env/site.yml

Pull request for final preparations of the Adobe integrations release.

Adobe Integrations - Release Candidate.

---

env/includes/engine_locations.yml

- Add BackBurner job completion option to engine
- Show publisher window when sending a job to burn

Update tk-flame to v1.14.9

---

env/includes/app_locations.yml
env/includes/engine_locations.yml

Merging apps and engines updates from release/v1.2.7 branch into master

Merging release/v1.2.7

---

env/includes/engine_locations.yml

JIRA: SMOK-51794
Shotgun batch render do not set assetType correctly

Update to tk-flame 1.15.3

---

env/includes/app_locations.yml
env/includes/frameworks.yml
env/includes/settings/tk-maya.yml
env/includes/settings/tk-multi-reviewsubmission.yml
env/includes/settings/tk-photoshopcc.yml

JIRA: VMR-2289
DESCRIPTION
Updates the tk-multi-reviewsubmission used in the config so the photoshop and
maya can have the new feature of Submit for review.

Add Playblast to Create and Submit for review

---

env/includes/settings/tk-3dsmax.yml
env/includes/settings/tk-multi-setframerange.yml

Adds settings for set frame range.

SG-15478: Config changes for 3dsmax and setframerange

---

env/includes/settings/tk-multi-shotgunpanel.yml

Adds missing hook to 3dsmaxplus's panel settings.

SG-15630: alembic panel fix

---

env/includes/frameworks.yml

Add the new tk-framework-aliastranslations to the config

Add Alias Translations Framework

---

env/includes/settings/tk-multi-loader2.yml

Simply enabling import of a VRED file into VRED.

Enable Importing of VRED file into VRED file

---

env/includes/settings/tk-multi-loader2.yml
env/includes/settings/tk-multi-shotgunpanel.yml

* Add action mappings for Alias loader and shotgunpanel: .tif and .bmp published file types to texture_node action

[SHOT-3464] Improve Naming

---

env/includes/engine_locations.yml

- Update to python 3
- Enable shotgun command line jobs in backburner if available

Update to Flame v1.16.2

---

core/hooks/pick_environment.py
env/includes/settings/tk-multi-shotgunpanel.yml
env/includes/settings/tk-shotgun-launchvredreview.yml
env/includes/settings/tk-shotgun.yml
env/includes/settings/tk-vred.yml
env/playlist.yml

Similar to tk-config-basic PR https://github.com/shotgunsoftware/tk-config-basic/pull/101, but for default2

SHOT-3556: Add environment for Playlist entity type

---

env/includes/app_locations.yml
env/includes/engine_locations.yml

JIRA: FLME-58258 FLME-53905 FLME-58463
FLME-58258 - Add configuration token/env var to change command job priority
FLME-53905 - Use Flame's python API execute_command() to start subprocesses
FLME-58463 - Avoid refreshing credentials if not expired

Update to tk-flame v1.17.0 and tk-flame-export v1.10.4

---

env/includes/frameworks.yml

Reverts shotgunsoftware/tk-config-default2#116

Revert "Update tk-framework-desktopclient"

---

README.md
env/includes/settings/tk-multi-publish2.yml

This PR replaces ZD urls to AKN and developer urls

SG-21170 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

env/README.md

This PR replaces ZD urls to AKN and developer urls

SG-21170-ROUND3 [ZD to AKN] Update links referenced from code to the old support site to point to AKN

---

env/includes/settings/tk-multi-publish2.yml

Replace 3D Version boolean config setting with Version Type string config setting, where Version Type is just the default value (e.g. 2D Version or 3D Version) and this option is then editable via the UI

SHOT-3905: Update config settings for Alias/VRED upload version publish plugin

---

env/includes/settings/tk-houdini.yml
env/includes/settings/tk-multi-workfiles2.yml

For new Workfiles2 App changes to the view, we need to add a custom hook for Houdini styling.

SG-31598: Add custom hook for Houdini tk-multi-workfiles2

---

env/includes/settings/tk-multi-shotgunpanel.yml

Config update to support https://github.com/shotgunsoftware/tk-alias/pull/176

SHOT-3854:  Add ShotGrid Panel action for Alias to import a note attachment.

---

env/includes/frameworks.yml

~~* Wait to merge until tk-alias v3.0.3 is released~~

Bump framework back up to v0.2.4 now that tk-alias v 3.0.3 is released.

---

env/includes/settings/tk-multi-breakdown2.yml

* Add remove reference as an additional action to file items in Breakdown2 for VRED
* This is an example of how to add custom actions to file items in Breakdown2
_Requires_
- https://github.com/shotgunsoftware/tk-vred/pull/113
- https://github.com/shotgunsoftware/tk-alias/pull/187
~~_**Do not merge until tk-alias and tk-vred released to include the above changes**_~~
tk-alias v3.2.0 and tk-vred v3.2.0 released to support this config update

SHOT-4292: Add custom actions for Breakdown2 in VRED

---

env/includes/software_paths.yml

Update default Mari software path to latest version.

SG-35128 Update Mari software path to version 7

---

env/includes/settings/tk-multi-workfiles2.yml

* Fixes issue with file view background color (as also was an issue with Houdini)
Requires https://github.com/shotgunsoftware/tk-3dsmax/pull/37

SG-34879: Add custom hook for 3ds Max to style Workfiles App

---

env/includes/frameworks.yml

* Toolkitty does not automatically add a new major version for frameworks

Add new major version for tk-framework-alias

---

env/includes/frameworks.yml

Reverts 714078549f73301a3e0cd05328c91afed6c11190

Revert tk-framework-alias to v2.1.3

---

env/includes/software_paths.yml

Switch MotionBuilder path from 2025 to 2026
Related to shotgunsoftware/tk-motionbuilder#35

SG-38379 Switch MotionBuilder path from 2025 to 2026

---

env/README.md

This pull request updates the support contact information to the current Autodesk support page.
The same change was done in the following repositories:
| Repo | PR |
|------|----|
| python-api | shotgunsoftware/python-api#411 |
| tk-3dsmax | shotgunsoftware/tk-3dsmax#54 |
| tk-aftereffects | shotgunsoftware/tk-aftereffects#61 |
| tk-alias | shotgunsoftware/tk-alias#221 |
| tk-config-default2 | shotgunsoftware/tk-config-default2#187 |
| tk-config-rv | shotgunsoftware/tk-config-rv#11 |
| tk-core | shotgunsoftware/tk-core#1054 |
| tk-desktop | shotgunsoftware/tk-desktop#204 |
| tk-desktop2 | shotgunsoftware/tk-desktop2#47 |
| tk-flame | shotgunsoftware/tk-flame#156 |
| tk-flame-export | shotgunsoftware/tk-flame-export#61 |
| tk-flame-review | shotgunsoftware/tk-flame-review#40 |
| …

SG-40165 Update Support URL
